fix(ts): TS2741
cast `schema` to argument of type `yaml.Schema`

lib/plugins/renderer/yaml.ts:19:41 - error TS2741:
Property 'extend' is missing in type 'Record<string, any>' but required
in type 'Schema'.